name: Config Page Decorator
description: Provides a Config Page decorator class for the Entity Decorator API
type: module
core_version_requirement: ^9.5 || ^10
version: 1.0.0
project: "config_page_decorator"
package: "Entity Decorator API"
dependencies:
  - entity_decorator_api:entity_decorator_api
  - config_pages:config_pages
